# Sandrine Burriel <sandrine@bureau-cornavin.com>, 2016.
# Éric Bischoff <ebischoff@bureau-cornavin.com>, 2016.
msgid ""
msgstr ""
"Project-Id-Version: univention-lib\n"
"Report-Msgid-Bugs-To: forge.univention.org\n"
"POT-Creation-Date: 2017-04-14 00:29+0200\n"
"PO-Revision-Date: 2016-06-20 19:12+0100\n"
"Last-Translator: Éric Bischoff <ebischoff@bureau-cornavin.com>\n"
"Language-Team: French <fr@bureau-cornavin.com>\n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"
"X-Generator: Lokalize 2.0\n"

#: python/package_manager.py:783
msgid "Autoremove failed"
msgstr "Échec de la suppression automatique"

#: python/package_manager.py:701 python/package_manager.py:702
msgid "Could not initialize package manager."
msgstr "Impossible d'initialiser le gestionnaire de paquetages."

#: python/package_manager.py:777
#, python-format
msgid "Deleting unneeded %s"
msgstr "Suppression de %s superflus"

#: python/package_manager.py:740
msgid "Error: "
msgstr "Erreur : "

#: python/package_manager.py:665
msgid "Failed to install"
msgstr "Échec de l'installation"

#: python/package_manager.py:313 python/package_manager.py:445
msgid "Failed to lock"
msgstr "Échec du verrouillage"

#: python/package_manager.py:670
msgid "Failed to uninstall"
msgstr "Échec de la désinstallation"

#: python/package_manager.py:440 python/package_manager.py:651
msgid "Fetching failed"
msgstr "Échec de la récupération"

#: python/package_manager.py:764
msgid "Further information regarding this error:"
msgstr "Informations complémentaires au sujet de cette erreur :"

#: python/package_manager.py:471
msgid "No such package"
msgstr "Paquetage inconnu"

#. i18n: "using it" refers to the "package manager"
#: python/package_manager.py:754
msgid ""
"Probably another process is currently using it or the package sources are "
"corrupt. Please try again later."
msgstr ""
"Un autre processus est probablement en train de l'utiliser ou les sources "
"des paquetages sont corrompues. Veuillez réessayer ultérieurement."

#: python/package_manager.py:751
msgid ""
"Some package conflicts could not be resolved. This was probably caused by "
"packages with \"hold\" state."
msgstr ""
"Certains conflits entre paquetages n'ont pas pu être résolus. Cela est "
"probablement dû à des paquetages en état « suspendu »."

#: python/package_manager.py:757
msgid "The package sources are probably corrupt."
msgstr "Les sources des paquetages sont probablement corrompues."

#: python/package_manager.py:760
msgid ""
"The sources.list entries could be repaired by executing the following "
"commands as root on this server:"
msgstr ""
"Les déclarations de sources.list peuvent être réparées en exécutant sur ce "
"serveur, en tant qu'utilisateur root, les commandes suivantes :"

#: python/package_manager.py:749
msgid "There is no free hard disk space left on the device."
msgstr "Il n'y a plus d'espace disponible sur le disque dur."

#: python/package_manager.py:579
msgid "Untrusted origin"
msgstr "Origine qui n'est pas de confiance"

#: python/package_manager.py:739
msgid "Warning: "
msgstr "Avertissement :"
